# [define]
# "process.env.DYLD_LIBRARY_PATH"=
# Bun's runtime behavior is configured using top-level fields in the bunfig.toml file.
[loader]
".dylib" = "file"
".so.*" = "file"
".dll" = "file"

[install]
# To configure Bun's package auto-install behavior.
# Default "auto" — when no node_modules folder is found, Bun
# will automatically install dependencies on the fly during execution.
# auto = true

# where `bun install --global` installs packages
globalDir = "~/.agents-fun/bun/install/global"

# where globally-installed package bins are linked
globalBinDir = "~/.agents-fun/bin"

# whether to install optionalDependencies (currently needed because all drivers are optional)
optional = true

# whether to install devDependencies
dev = true

# whether to install peerDependencies
peer = true

# equivalent to `--production` flag
production = false

# equivalent to `--frozen-lockfile` flag
frozenLockfile = false

# equivalent to `--dry-run` flag
dryRun = false

# equivalent to `--concurrent-scripts` flag
# concurrentScripts = 16 # (cpu count or GOMAXPROCS) x2

# [install.scopes]
# registry as string
# myorg = "https://username:password@registry.myorg.com/"

# registry with username/password
# you can reference environment variables
# myorg = { username = "myusername", password = "$npm_password", url = "https://registry.myorg.com/" }

# registry with token
# myorg = { token = "$npm_token", url = "https://registry.myorg.com/" }

[install.cache]
# the directory to use for the cache
dir = ".agents-fun/install/cache"

# when true, don't load from the global cache.
# Bun may still write to node_modules/.cache
disable = false

# when true, always resolve the latest versions from the registry
disableManifest = false

[install.lockfile]

# whether to save the lockfile to disk
save = true

[run]
# equivalent to `bun --bun` for all `bun run` commands
bun = true
