name: Verify Package Version

on:
  pull_request:
    branches:
      - main
    paths:
      - 'agents-fun/package.json'

permissions:
  contents: read

jobs:
  verify-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current package.json version
        id: package_version
        run: |
          echo "version=$(jq -r '.version' agents-fun/package.json)" >> $GITHUB_OUTPUT

      - name: Get latest GitHub release version
        id: latest_release
        uses: actions/github-script@v7
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            const latestRelease = releases.data[0];
            const latestVersion = latestRelease ? latestRelease.tag_name.replace(/^v/, '') : '0.0.0';
            core.setOutput('version', latestVersion);

      - name: Compare versions
        run: |
          PACKAGE_VERSION=${{ steps.package_version.outputs.version }}
          LATEST_VERSION=${{ steps.latest_release.outputs.version }}

          echo "Package version: $PACKAGE_VERSION"
          echo "Latest release version: $LATEST_VERSION"

          if [ "$(printf '%s\n%s' "$LATEST_VERSION" "$PACKAGE_VERSION" | sort -V | tail -n1)" != "$PACKAGE_VERSION" ] || [ "$PACKAGE_VERSION" = "$LATEST_VERSION" ]; then
            echo "Error: package.json version ($PACKAGE_VERSION) must be greater than latest release version ($LATEST_VERSION)."
            exit 1
          else
            echo "Version check passed."
          fi